### ISSUE TITLE
Documentation changes

### ISSUE THREAD

**Issue by abose** [phcode-dev/docs#16]
Add the following sessions in phoenix:
![image](https://user-images.githubusercontent.com/5336369/159154446-1c8bb7e4-8fcd-440d-8c3f-916af7d57354.png)

1. SVG logo of phoenix at top bar (logo SVG attached).
2. Discord icon at top right pointing to URL: https://discord.com/invite/rBpTBPttca 
![image](https://user-images.githubusercontent.com/5336369/159154027-5309028c-17b5-4f61-af5c-790c8d7c3ae1.png)
3. `Copyright © core.ai 2022 All rights reserved` at bottom left
4. Change main doc text and link to AGPL licence ![image](https://user-images.githubusercontent.com/5336369/159154019-012ceca5-10d3-4d4a-a1b1-86517775c6a8.png)

## Add the following placeholder documents
1. `Quick start` under `Getting started` menu
2. `Live preview` under `docs`
3. `Extensions API` under `API`

## Icons
Phoenix, discord attached file below
[icons.zip](https://github.com/phcode-dev/docs/files/8310853/icons.zip)

**Comment by abose** [comment]
Thanks @dhruvpeter for the chanegs
LGTM Merging

## Rending things:
Hyperlink the following
1. `Quick Start` to http://.../docs/prologue/quick-start/
2. `Live Preview to` to http://.../docs/livePreview/
3. `Extensions API` to http://.../api/

**Comment by abose** [comment]
Thanks, @dhruvpeter for the changes.
For some URLs we are getting 404, can we have a blank document in that location too.
![image](https://user-images.githubusercontent.com/5336369/159468301-159b419c-23b8-44e2-8020-a90c1cf97646.png)

**Comment by dhruvpeter** [comment]
All document changes mentioned are done.

**Comment by abose** [comment]
Verified done. Closing.
Thanks @dhruvpeter
